# Generated by Django 5.0.3 on 2025-05-28

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        # Add the cart_id column if it doesn't exist
        migrations.RunSQL(
            """
            ALTER TABLE store_order 
            ADD COLUMN IF NOT EXISTS cart_id INT NULL;
            """
        ),
        # Set up the OneToOneField relationship
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(
                on_delete=models.SET_NULL,
                null=True,
                blank=True,
                related_name='order',
                to='store.cart'
            ),
        ),
    ]
