# Generated by Django 5.0.3 on 2025-05-28

from django.db import migrations, models

def migrate_cart_relationship(apps, schema_editor):
    """Migrate existing orders to have a cart relationship if they don't have one."""
    Order = apps.get_model('store', 'Order')
    Cart = apps.get_model('store', 'Cart')
    
    # First add the column if it doesn't exist
    try:
        schema_editor.execute("""
            ALTER TABLE store_order 
            ADD COLUMN IF NOT EXISTS cart_id INT NULL;
        """)
    except Exception as e:
        print(f"Error adding column: {e}")
    
    # Then migrate existing data
    for order in Order.objects.all():
        if not order.cart_id and order.user_id:
            # Try to find or create a cart for this user
            cart, created = Cart.objects.get_or_create(user_id=order.user_id)
            order.cart = cart
            order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        # Add the cart_id column first
        migrations.RunSQL(
            """
            ALTER TABLE store_order 
            ADD COLUMN IF NOT EXISTS cart_id INT NULL;
            """
        ),
        # Run data migration
        migrations.RunPython(migrate_cart_relationship),
        # Then alter the field to be a proper OneToOneField
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(
                on_delete=models.SET_NULL,
                null=True,
                blank=True,
                related_name='order',
                to='store.cart'
            ),
        ),
    ]
