# Generated by Django 5.0.3 on 2025-05-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
    ]
