# Generated by Django 5.0.3 on 2025-05-16 11:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-16 11:50:00'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2025-05-16 11:50:00'),
        ),
    ]
