# Generated by Django 5.0.3 on 2025-05-28

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_fix_cart_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
