# Generated by Django 5.0.3 on 2025-05-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_orderitem_options_alter_orderitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='razorpay order id'),
        ),
    ]
