# Generated by Django 5.0.3 on 2025-05-29 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_fix_cart_relationship_again'),
        ('store', '0004_fix_cart_relationship_final'),
    ]

    operations = [
    ]
