# Generated by Django 5.0.3 on 2025-05-30 09:11

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_add_cart_field_to_order'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE store_cart 
            DROP COLUMN IF EXISTS item_count;
            """,
            # Reverse SQL (if needed, though it's not reversible)
            reverse_sql="""
            ALTER TABLE store_cart 
            ADD COLUMN item_count INT DEFAULT 0;
            """
        ),
    ]
