# Generated by Django 5.0.3 on 2025-05-30 09:11

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_add_cart_field_to_order'),
    ]

    operations = [
        migrations.RunSQL(
            """
            SET @dbname = DATABASE();
            SET @tablename = 'store_cart';
            SET @columnname = 'item_count';
            SET @preparedStatement = (SELECT IF(
              EXISTS (
                  SELECT * FROM INFORMATION_SCHEMA.COLUMNS
                  WHERE (table_schema = @dbname)
                    AND (table_name = @tablename)
                    AND (column_name = @columnname)
              ),
              CONCAT('ALTER TABLE ', @tablename, ' DROP COLUMN ', @columnname, ';'),
              'SELECT 1;'
            ));
            PREPARE alterIfExists FROM @preparedStatement;
            EXECUTE alterIfExists;
            DEALLOCATE PREPARE alterIfExists;
            """,
            # Reverse SQL (if needed, though it's not reversible)
            reverse_sql="""
            ALTER TABLE store_cart 
            ADD COLUMN item_count INT DEFAULT 0;
            """
        ),
    ]
