# Generated by Django 5.0.3 on 2025-05-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_add_total_to_cart'),
        ('store', '0007_clean_duplicate_carts'),
    ]

    operations = [
    ]
