[build]
  command = "python manage.py collectstatic --noinput"
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/django"
  status = 200
