services:
  - type: web
    name: angel-plants
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn angels_plants.wsgi:application"
    envVars:
      # Core Django Settings
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: PYTHONUNBUFFERED
        value: "True"
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "angels_plants.settings"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      
      # Database Configuration
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"
      - key: DB_NAME
        value: "angel_plants_new_db"
      - key: DB_USER
        value: "angel_plants_new_db_user"
      - key: DB_PASSWORD
        value: "YigjIH5nafM55UYAx3TGoWFfZFK4PxvS"
      - key: DB_HOST
        value: "dpg-d0q432vdiees738nsqb0-a"
      - key: DB_PORT
        value: "5432"
      - key: DB_SSLMODE
        value: "require"
      
      # Razorpay Configuration
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      
      # Email Configuration
      - key: SENDGRID_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: CONTACT_EMAIL
        sync: false
    # Auto-deploy from GitHub
    autoDeploy: true
    # Health check path
    healthCheckPath: "/"
    # Plan selection - free/standard/plus/pro
    plan: free
    # Region - choose closest to your users
    region: oregon
    # Python version
    pythonVersion: "3.9.0"
    # Environment variables map
    envVarsMap: {}

# Database configuration
databases:
  - name: angel-plants-db
    databaseName: angel_plants_new_db
    user: angel_plants_new_db_user
    password: YigjIH5nafM55UYAx3TGoWFfZFK4PxvS
    host: dpg-d0q432vdiees738nsqb0-a
    port: 5432
    # Database plan - free/standard/plus/pro
    plan: free
    # Database region - should match web service region
    region: Singapore (Southeast Asia)
    # Connection string for Django
    connectionString: postgresql://angel_plants_new_db_user:YigjIH5nafM55UYAx3TGoWFfZFK4PxvS@dpg-d0q432vdiees738nsqb0-a:5432/angel_plants_new_db
