services:
  - type: web
    name: angel-plants
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn angels_plants.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: PYTHONUNBUFFERED
        value: "True"
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "angels_plants.settings"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      # Add your other environment variables here
      # These should be set in the Render dashboard
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: CONTACT_EMAIL
        sync: false
    # Auto-deploy from GitHub
    autoDeploy: true
    # Health check path
    healthCheckPath: "/"
    # Plan selection - free/standard/plus/pro
    plan: free
    # Region - choose closest to your users
    region: oregon
    # Python version
    pythonVersion: "3.9.0"
    # Environment variables map
    envVarsMap: {}

# Database configuration
databases:
  - name: angel-plants-db
    databaseName: angel_plants
    user: angel_plants_user
    # Database plan - free/standard/plus/pro
    plan: free
    # Database region - should match web service region
    region: oregon
