services:
  - type: web
    name: angel-plants
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn angels_plants.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: DATABASE_URL
        fromDatabase:
          name: angel-plants-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DISABLE_COLLECTSTATIC
        value: "1"

databases:
  - name: angel-plants-db
    databaseName: angel_plants
    user: angel_plants_user
    plan: free
