# Generated by Django 5.0.3 on 2025-06-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_user_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='address2',
            field=models.TextField(blank=True, null=True, verbose_name='address line 2'),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='district'),
        ),
    ]
