# Generated by Django 5.0.3 on 2025-06-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_add_status_changed_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='actual delivery date'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='delivery instructions'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='estimated delivery date'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'Standard Shipping (5-7 business days)'), ('express', 'Express Shipping (2-3 business days)'), ('same_day', 'Same Day Delivery (if ordered before 12 PM)'), ('store_pickup', 'Store Pickup')], default='standard', max_length=20, verbose_name='shipping method'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='shipping provider'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready_for_shipment', 'Ready for Shipment'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_changed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='status changed'),
        ),
        migrations.CreateModel(
            name='OrderStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='status')),
                ('status_display', models.CharField(max_length=100, verbose_name='status display')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='store.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order status update',
                'verbose_name_plural': 'order status updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
